#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate SkillInfoList.lub from skill_dump.txt and SKILL_NAME_MAP.

Reads:
  - tools/extracted/skill_dump.txt (EUC-KR, tab-separated)
  - tools/translate_skills.py (SKILL_NAME_MAP dict)

Writes:
  - client/data/luafiles514/lua files/skillInfoz/SkillInfoList.lub (Big5, CRLF)
"""

import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(TOOLS_DIR)
DUMP_FILE = os.path.join(TOOLS_DIR, "extracted", "skill_dump.txt")
OUTPUT_DIR = os.path.join(
    PROJECT_DIR, "client", "data", "luafiles514", "lua files", "skillInfoz"
)
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "SkillInfoList.lub")

# Import SKILL_NAME_MAP from translate_skills.py
sys.path.insert(0, TOOLS_DIR)
from translate_skills import SKILL_NAME_MAP


def parse_dump_file(filepath):
    """Parse skill_dump.txt (EUC-KR encoded, tab-separated).

    Fields: id, skill_id, name, maxlv, sp_amounts, separate_lv, attack_range
    """
    with open(filepath, "rb") as f:
        raw = f.read()
    text = raw.decode("euc-kr", errors="replace")

    skills = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split("\t")
        if len(parts) < 6:
            print(f"  WARNING: skipping malformed line ({len(parts)} fields): {parts}")
            continue

        db_id = int(parts[0])
        skill_id = parts[1]       # e.g. "SM_BASH"
        kr_name = parts[2]        # Korean name
        max_lv = int(parts[3])
        sp_str = parts[4]         # e.g. "8,8,8,15,15"
        sep_lv_str = parts[5]     # "true" or "false"
        range_str = parts[6] if len(parts) >= 7 else ""  # may be missing

        # Parse SP amounts
        if sp_str.strip():
            sp_amounts = [int(x) for x in sp_str.split(",")]
        else:
            sp_amounts = []

        # Parse separate level
        separate_lv = sep_lv_str.strip().lower() == "true"

        # Parse attack range
        if range_str.strip():
            attack_range = [int(x) for x in range_str.split(",")]
        else:
            attack_range = []

        skills.append({
            "db_id": db_id,
            "skill_id": skill_id,
            "kr_name": kr_name,
            "max_lv": max_lv,
            "sp_amounts": sp_amounts,
            "separate_lv": separate_lv,
            "attack_range": attack_range,
        })

    return skills


def get_chinese_name(skill_id, kr_name):
    """Get Chinese name for a skill, with fallback to English skill_id."""
    if skill_id in SKILL_NAME_MAP:
        zh_name = SKILL_NAME_MAP[skill_id]
        # Verify it can be encoded in Big5
        try:
            zh_name.encode("big5")
            return zh_name, "translated"
        except UnicodeEncodeError:
            # Fall back to English skill_id
            fallback = skill_id.replace("_", " ")
            return fallback, "big5_fallback"
    else:
        # No translation available — use English skill_id formatted
        fallback = skill_id.replace("_", " ")
        return fallback, "untranslated"


def format_lua_list(values):
    """Format a Python list as a Lua table literal: { 1, 2, 3 }"""
    if not values:
        return "{ }"
    return "{ " + ", ".join(str(v) for v in values) + " }"


def generate_lua(skills):
    """Generate the Lua file content as a Unicode string."""
    lines = []
    lines.append("-- SkillInfoList.lub")
    lines.append("-- Auto-generated by gen_skill_info_list.py")
    lines.append("-- Encoding: Big5")
    lines.append("")
    lines.append("SKILL_INFO_LIST = {}")
    lines.append("")

    # Sort skills by db_id for consistent ordering
    skills_sorted = sorted(skills, key=lambda s: s["db_id"])

    # Track stats
    translated = 0
    fallback = 0
    big5_fallback = 0
    skipped = 0

    # Track seen skill_ids to avoid duplicates (dump may have dupes)
    seen_skill_ids = set()

    for skill in skills_sorted:
        skill_id = skill["skill_id"]

        # Skip duplicate skill_ids (keep first occurrence by db_id order)
        if skill_id in seen_skill_ids:
            continue
        seen_skill_ids.add(skill_id)

        # Skip skills with UNKNOWN_ prefix or NPC_ prefix skills that
        # don't have SKID mappings, or skills with max_lv = 0
        if skill_id.startswith("UNKNOWN_"):
            skipped += 1
            continue

        # Get the Chinese name
        zh_name, source = get_chinese_name(skill_id, skill["kr_name"])
        if source == "translated":
            translated += 1
        elif source == "big5_fallback":
            big5_fallback += 1
        else:
            fallback += 1

        max_lv = skill["max_lv"]

        # Handle edge case: max_lv = 0 means no real skill data
        if max_lv <= 0:
            # Still generate entry but with empty arrays
            sp_str = "{ }"
            range_str = "{ }"
            sep_lv = "false"
        else:
            sp_str = format_lua_list(skill["sp_amounts"])
            range_str = format_lua_list(skill["attack_range"])
            sep_lv = "true" if skill["separate_lv"] else "false"

        # Escape quotes in skill name for Lua string
        lua_name = zh_name.replace("\\", "\\\\").replace('"', '\\"')

        lines.append(f'SKILL_INFO_LIST[SKID.{skill_id}] = {{')
        lines.append(f'    SkillName = "{lua_name}",')
        lines.append(f'    MaxLv = {max_lv},')
        lines.append(f'    SpAmount = {sp_str},')
        lines.append(f'    bSeperateLv = {sep_lv},')
        lines.append(f'    AttackRange = {range_str},')
        lines.append(f'}}')
        lines.append('')

    print(f"\n  Stats:")
    print(f"    Total skills processed: {len(seen_skill_ids)}")
    print(f"    Translated (Chinese):   {translated}")
    print(f"    Big5 encode fallback:    {big5_fallback}")
    print(f"    English fallback:        {fallback}")
    print(f"    Skipped (UNKNOWN_):      {skipped}")

    return "\n".join(lines)


def main():
    print("=" * 60)
    print("Generating SkillInfoList.lub")
    print("=" * 60)

    # Parse dump file
    print(f"\n[Step 1] Parsing {DUMP_FILE}...")
    skills = parse_dump_file(DUMP_FILE)
    print(f"  Loaded {len(skills)} skill entries")

    # Generate Lua content
    print(f"\n[Step 2] Generating Lua content...")
    lua_content = generate_lua(skills)

    # Encode to Big5
    print(f"\n[Step 3] Encoding to Big5 and writing...")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Encode to Big5 — characters that can't encode get replaced with '?'
    try:
        big5_bytes = lua_content.encode("big5")
    except UnicodeEncodeError as e:
        print(f"  ERROR: Big5 encoding failed at position {e.start}: {e.reason}")
        print(f"  Problematic text: ...{lua_content[max(0,e.start-20):e.start+20]}...")
        sys.exit(1)

    # Convert LF to CRLF
    big5_bytes = big5_bytes.replace(b"\n", b"\r\n")

    with open(OUTPUT_FILE, "wb") as f:
        f.write(big5_bytes)

    print(f"  Written to: {OUTPUT_FILE}")
    print(f"  File size: {len(big5_bytes)} bytes")

    # Verify
    print(f"\n[Step 4] Verifying output...")
    with open(OUTPUT_FILE, "rb") as f:
        content = f.read()

    try:
        decoded = content.decode("big5")
        line_count = decoded.count("\n") + 1
        print(f"  Big5 decode: OK")
        print(f"  Line count: {line_count}")
    except UnicodeDecodeError as e:
        print(f"  Big5 decode: FAILED at byte {e.start}")
        sys.exit(1)

    # Check CRLF
    crlf_count = content.count(b"\r\n")
    lf_only = content.count(b"\n") - crlf_count
    print(f"  CRLF line endings: {crlf_count}")
    if lf_only > 0:
        print(f"  WARNING: {lf_only} bare LF found")
    else:
        print(f"  No bare LF (good)")

    # Show first few entries as preview
    print(f"\n[Preview] First 30 lines:")
    preview_lines = decoded.split("\n")[:30]
    for line in preview_lines:
        print(f"  {line.rstrip()}")

    print(f"\n{'=' * 60}")
    print("Done!")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
